plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.flyyye.petpark'
    compileSdk 34

    defaultConfig {
        applicationId "cn.flyyye.petpark"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file("../petpark.keystore")
            storePassword "petpark2468"
            keyAlias "petpark"
            keyPassword "petpark2468"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
